"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 2000

format = """
[](surface0)\
$os\
$username\
[](bg:peach fg:surface0 bold)\
$directory\
[](fg:peach bg:green bold)\
$git_branch\
$git_status\
[](fg:green bg:teal bold)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:teal bg:blue bold)\
$docker_context\
[](fg:blue bg:purple bold)\
$time\
[ ](fg:purple)\
$line_break$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
orange = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
disabled = false
style = "bg:surface0 fg:text bold"

[os.symbols]
Windows = "󰍲"  # NF_WINDOWS
Ubuntu = "󰕈"  # NF_Ubuntu
SUSE = ""    # NF_SUSE
Raspbian = "󰐿"  # NF_Raspbian
Mint = "󰣭"    # NF_Linux_Mint
Macos = ""    # NF_APPLE
Manjaro = ""  # NF_MANJARO
Linux = "󰌽"   # NF_LINUX
Gentoo = "󰣨"  # NF_GENTOO
Fedora = "󰣛"  # NF_FEDORA
Alpine = ""   # NF_ALPINE
Amazon = ""  # NF_AMAZON
Android = ""  # NF_ANDROID
Arch = "󰣇"    # NF_ARCH_LINUX
Artix = "󰣇"   # NF_ARTIX
CentOS = ""  # NF_CENTOS
Debian = "󰣚"  # NF_DEBIAN
Redhat = "󱄛"  # NF_REDHAT
RedHatEnterprise = "󱄛"  # NF_REDHAT_ENTERPRISE

[username]
show_always = true
style_user = "bg:surface0 fg:text bold"
style_root = "bg:surface0 fg:red bold"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bg:peach bold"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol $branch ](fg:base bg:green bold)]($style)'

[git_status]
style = "bg:teal fg:base bold"
format = '[[($all_status$ahead_behind)](fg:base bg:green bold)]($style)'

[nodejs]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[c]
symbol = " "
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[rust]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[golang]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[php]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[java]
symbol = " "
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[kotlin]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[haskell]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[python]
symbol = ""
style = "bg:teal fg:base bold"
format = '[[ $symbol( $version) ](fg:base bg:teal bold)]($style)'

[docker_context]
symbol = ""
style = "bg:mantle fg:#83a598 bold"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3 bold)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach bold"
format = '[[  $time ](fg:mantle bg:purple bold)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:cyan)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
